import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { IdentityKitProvider } from "@nfid/identitykit/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <IdentityKitProvider
          authType="DELEGATION"
          signerClientOptions={{
            targets: [
              "aaaaa-aa",
            ],
          }}
        >
          {children}
        </IdentityKitProvider>
      </body>
    </html>
  );
}
